"""Compatibility evidence is generated by the actual pinned release in isolation."""

import json
import os
import shutil
import subprocess
import tarfile
from pathlib import Path

import pytest

RELEASE = "9779108188cadff87d2ff9ee321b491d8ec16b68"


def release_fixture(tmp_path_factory, tag, release):
    root = tmp_path_factory.mktemp(tag)
    source = root / "source"
    source.mkdir()
    archive = root / "release.tar"
    repo = Path(__file__).resolve().parents[1]
    assert (
        subprocess.check_output(
            ["git", "rev-parse", tag + "^{}"], cwd=repo, text=True
        ).strip()
        == release
    )
    with archive.open("wb") as output:
        subprocess.run(["git", "archive", release], cwd=repo, stdout=output, check=True)
    with tarfile.open(archive) as bundle:
        bundle.extractall(source, filter="data")
    env = {
        k: v for k, v in os.environ.items() if k not in ("VIRTUAL_ENV", "PYTHONPATH")
    }
    subprocess.run(
        ["uv", "sync", "--frozen", "--python", "3.14.5"],
        cwd=source,
        env=env,
        check=True,
        capture_output=True,
    )
    python = source / ".venv/bin/python"
    database = root / "v1.sqlite3"
    script = """
import importlib, json, sys
from blackbox.db import connect, schema_digest
from blackbox.ingest import ingest, append_claim
from blackbox.query import reconstruct, integrity
from blackbox.schema import DDL
from blackbox.models import identity
m = importlib.import_module("blackbox.ingest")
request = {"request_id": "released", "producer": "release-test",
 "observations": [{"source":"caller", "kind":"test", "name":"released"}],
 "claims": [{"source":"caller", "topic":"release", "statement":"Initial claim"}],
 "artifacts": [{"source":"caller", "path":"report.txt", "digest":"a"*64}]}
original = m.claim_row
m.claim_row = lambda *a, **kw: (_ for _ in ()).throw(OSError("synthetic"))
try:
    ingest(sys.argv[1], request)
except OSError:
    pass
m.claim_row = original
session = ingest(sys.argv[1], request)["session_id"]
old = reconstruct(sys.argv[1], session)["claims"][0]["id"]
new = append_claim(sys.argv[1], session,
 {"source":"reviewer", "topic":"release", "statement":"Correction"},
 target=old, relation="supersedes")
append_claim(sys.argv[1], session,
 {"source":"reviewer", "topic":"release", "statement":"Dispute"},
 target=new, relation="contests")
# A real Git observation preserves the second authority/verification class.
other = ingest(sys.argv[1], {"request_id":"git", "producer":"release-test"}, repo=sys.argv[2])["session_id"]
# Leave a durable reservation, as a process interruption would.
reserved_request = {**request, "request_id": "reserved"}
m.claim_row = lambda *a, **kw: (_ for _ in ()).throw(SystemExit(73))
try:
    ingest(sys.argv[1], reserved_request)
except SystemExit:
    pass
reserved = identity("ses", "reserved")
assert reconstruct(sys.argv[1], reserved)["status"] == "RESERVED"
assert integrity(sys.argv[1])["ok"]
print(json.dumps({"ddl": DDL, "digest":schema_digest(),
 "records": [reconstruct(sys.argv[1], s) for s in (session, other, reserved)]}))
"""
    result = subprocess.run(
        [str(python), "-c", script, str(database), str(repo)],
        cwd=source,
        env=env,
        check=True,
        text=True,
        capture_output=True,
    )
    return database, json.loads(result.stdout), python, source, env


@pytest.fixture
def v1_database(released_v1, tmp_path):
    path = tmp_path / "v1.sqlite3"
    shutil.copy2(released_v1[0], path)
    return path


@pytest.fixture(scope="session")
def released_v1(tmp_path_factory):
    return release_fixture(tmp_path_factory, "v0.1.0", RELEASE)


@pytest.fixture(scope="session")
def released_v2(tmp_path_factory):
    return release_fixture(
        tmp_path_factory, "v0.3.0", "b2377d1214da2ac4c1df387b4ae2c7cd3e3aeebd"
    )


@pytest.fixture
def v2_database(released_v2, tmp_path):
    path = tmp_path / "v2.sqlite3"
    shutil.copy2(released_v2[0], path)
    return path


@pytest.fixture(scope="session")
def released_v3(tmp_path_factory):
    return release_fixture(
        tmp_path_factory, "v0.4.0", "dc503f597bc581aa4372091f6269543eaa251ea8"
    )


@pytest.fixture
def v3_database(released_v3, tmp_path):
    path = tmp_path / "v3.sqlite3"
    shutil.copy2(released_v3[0], path)
    return path
