"""Supported BlackBox API. Implementation submodules are not public contracts."""

from .api import (
    append_claim,
    capture,
    check_integrity,
    get_claims,
    get_session,
    get_timeline,
    initialize,
)
from .errors import (
    BlackBoxError,
    BusyError,
    ConflictError,
    DatabaseError,
    IntegrityError,
    MigrationRequiredError,
    NotFoundError,
    ObservationError,
    SchemaError,
    ValidationError,
)
from .results import (
    ArtifactRecord,
    CallerObservation,
    CaptureResult,
    ClaimRecord,
    ClaimResult,
    ClaimView,
    EvidenceRecord,
    FailureRecord,
    GitObservation,
    InitializationResult,
    IntegrityResult,
    ObservationRecord,
    SessionRecord,
    SessionView,
    SourceRecord,
    TimelineEvent,
)

__version__ = "0.3.0"
__all__ = [
    "ArtifactRecord",
    "BlackBoxError",
    "BusyError",
    "CallerObservation",
    "CaptureResult",
    "ClaimRecord",
    "ClaimResult",
    "ClaimView",
    "ConflictError",
    "DatabaseError",
    "EvidenceRecord",
    "FailureRecord",
    "GitObservation",
    "InitializationResult",
    "IntegrityError",
    "IntegrityResult",
    "MigrationRequiredError",
    "NotFoundError",
    "ObservationError",
    "ObservationRecord",
    "SchemaError",
    "SessionRecord",
    "SessionView",
    "SourceRecord",
    "TimelineEvent",
    "ValidationError",
    "__version__",
    "append_claim",
    "capture",
    "check_integrity",
    "get_claims",
    "get_session",
    "get_timeline",
    "initialize",
]
